server:
  port: 8500


#配置eureka信息
eureka:
  instance:
    hostname: localhost
  client:
    service-url: #eureka服务端地址，将来客户端使用该地址与eureka进行通信
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    # 是否将自己的路径 注册到eureka上。eureka server 不需要的，eureka provider client 需要
    register-with-eureka: false
    # 是否需要从eureka中抓取路径。eureka server 不需要的，eureka consumer client 需要
    fetch-registry: false