server:
  port: 9500

spring:
  application:
    name: gateway-server
  cloud:
    # 网关配置
    gateway:
      # 路由配置：转发规则
      routes: #集合。
        # id: 唯一标识。默认是一个UUID
        # uri: 转发路径
        # predicates: 条件,用于请求网关路径的匹配规则
        - id: eureka-provider
            # 静态路由
          # uri: http://localhost:8000/
            # 动态路由
          uri: lb://EUREKA-PROVIDER
          predicates:
            - Path=/Good/**
          #filters:
          #  - AddRequestParameter=username,zhangsan
      discovery:
        locator:
          enabled: true    #请求路径前可以添加微服务名称
          lower-case-service-id: true     #允许为小写

#配置eureka信息
eureka:
  instance:
    hostname: localhost
  client:
    service-url: #eureka服务端地址，将来客户端使用该地址与eureka进行通信
      defaultZone: http://${eureka.instance.hostname}:8500/eureka

